### ISSUE TITLE
Unexpected character encountered while parsing value: {. Path 'data', line 2, position 12

### ISSUE THREAD

**Issue by SHI-WEI** [snowflakedb/snowflake-connector-net#105]
When the SQL execution fails, sometimes the client has an exception.

```
Unexpected character encountered while parsing value: {. Path 'data', line 2, position 12. 
LastError.ToString() = System.Web.HttpException (0x80004005) ---> System.AggregateException: One or more errors occurred. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'data', line 2, position 12.
at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
at Newtonsoft.Json.JsonTextReader.ReadAsString()
at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
at Snowflake.Data.Core.RestRequestImpl.d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at Snowflake.Data.Core.RestRequestImpl.<>c__DisplayClass11_0`1.<b__0>d.MoveNext()
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
at Snowflake.Data.Core.RestRequestImpl.Post[T](SFRestRequest postRequest)
at Snowflake.Data.Core.SFSession.close()
at Snowflake.Data.Client.SnowflakeDbConnection.Close()
```

*Dotnet framework and version:* .NET Framework 4.6.2 - 4.7

*Server version:* 3.14.3

*Client OS:* Windows 10

**Comment by howryu** [comment]
@SHI-WEI  Do you have loggings enabled? From your description it seems error is thrown after query execution finished. However, from the stacktrace, it seems failed when closing the session.

**Comment by SHI-WEI** [comment]
> @SHI-WEI Do you have loggings enabled? From your description it seems error is thrown after query execution finished. However, from the stacktrace, it seems failed when closing the session.

We used Try/Catch when executing SQL statements.
When the SQL execution fails, no exception is thrown, but database connection is closed in the Catch.
The exception mentioned above appears in SnowflakeDbConnection.Close().

This issue didn't occur when we used the 1.0.6.0 version of the client.

**Comment by howryu** [comment]
@SHI-WEI I will close this issue since you mentioned that it did not happened in 1.0.6, feel free to open another one if you found it.
