### ISSUE TITLE
SNOW-1805438: BuildResultSet >> NullReferenceException

### ISSUE THREAD

**Issue by GSerjo** [snowflakedb/snowflake-connector-net#1059]
Please answer these questions before submitting your issue. 
In order to accurately debug the issue this information is required. Thanks!

1. What version of .NET driver are you using?
`<PackageReference Include="Snowflake.Data" Version="4.2.0" />`
   
2. What operating system and processor architecture are you using?
windows x64
   
3. What version of .NET framework are you using?
`net8.0`
   
4. What did you do?
called `ExecuteNonQueryAsync(cancellationToken);`  on `DbCommand`

6. What did you expect to see?
Descriptive error message: what was wrong. The current driver's implementation throws a `null reference` exception.

7. Can you set logging to DEBUG and collect the logs?

here's call stack
```csharp
System.NullReferenceException: Object reference not set to an instance of an object.
   at Snowflake.Data.Core.SFStatement.BuildResultSet(QueryExecResponse response, CancellationToken cancellationToken)
   at Snowflake.Data.Core.SFStatement.GetResultWithId(String resultId)
   at Snowflake.Data.Core.SFMultiStatementsResultSet.NextResult()
   at Snowflake.Data.Core.SFMultiStatementsResultSet..ctor(QueryExecResponseData responseData, SFStatement sfStatement, CancellationToken cancellationToken)
   at Snowflake.Data.Core.SFStatement.BuildResultSet(QueryExecResponse response, CancellationToken cancellationToken)
   at Snowflake.Data.Core.SFStatement.ExecuteAsync(Int32 timeout, String sql, Dictionary`2 bindings, Boolean describeOnly, Boolean asyncExec, CancellationToken cancellationToken)
   at Snowflake.Data.Client.SnowflakeDbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
```

Looks like the response is `null` somehow

```csharp
private SFBaseResultSet BuildResultSet(
      QueryExecResponse response,
      CancellationToken cancellationToken)
    {
      if (response.data != null && response.data.queryId != null)
        this._lastQueryId = response.data.queryId;
      if (!response.success)
        throw new SnowflakeDbException(response.data.sqlState, response.code, response.message, response.data.queryId);
      if (response.data.resultIds != null && response.data.resultIds.Length > 0)
        return (SFBaseResultSet) new SFMultiStatementsResultSet(response.data, this, cancellationToken);
      return response.data.queryResultFormat == ResultFormat.ARROW ? (SFBaseResultSet) new ArrowResultSet(response.data, this, cancellationToken) : (SFBaseResultSet) new SFResultSet(response.data, this, cancellationToken);
    }
```

Based on the call stack, here's what has been called before the exception

```csharp
public T Get<T>(IRestRequest request)
    {
      return Task.Run<T>((Func<Task<T>>) (async () => await this.GetAsync<T>(request, CancellationToken.None).ConfigureAwait(false))).Result;
    }

    public async Task<T> GetAsync<T>(IRestRequest request, CancellationToken cancellationToken)
    {
      T async;
      using (HttpResponseMessage response = await this.GetAsync(request, cancellationToken).ConfigureAwait(false))
        async = JsonConvert.DeserializeObject<T>(await response.Content.ReadAsStringAsync().ConfigureAwait(false), JsonUtils.JsonSettings);
      return async;
    }
```

Don't know the exact command's query params. It would be nice if the connector will  catch the exception and provide some details on what was wrong.

**Comment by sfc-gh-dszmolka** [comment]
hi - thanks for reporting this issue and the analysis ! we'll take a look

**Comment by sfc-gh-dszmolka** [comment]
fix in review: https://github.com/snowflakedb/snowflake-connector-net/pull/1061

**Comment by sfc-gh-dszmolka** [comment]
change released in .NET driver version 4.3.0
