### ISSUE TITLE
DB connection issues. Looks like the error is in db.Close()

### ISSUE THREAD

**Issue by Ferprimart** [snowflakedb/snowflake-connector-net#113]
### Issue description
Im facing issues with the connection to the DB. The main issue is that when we are closing the connection, our API is throwing an exception, not always but so many times.

My application it's a Web App that most of the times is receiving more than one API request at the same time. I'm using the same credentials for connecting to the DB in every API call I'm receiving. We were debugging our code and we saw that the API is throwing the exception when we are closing the connection with the DB (db.Close()); so probably we are not doing it in the right moment (in SQL Server was working without no problem). 

Thanks in advance.

### Example code
```cs

     using (IDbConnection conn = new SnowflakeDbConnection())
     {
            conn.ConnectionString = "account=XXX;host=YYY;user=ZZZ;password=UUU;warehouse=SSS";
            conn.Open();            
            IDbCommand cmd = conn.CreateCommand();
            cmd.CommandText = "SELECT * FROM TABLE";
            IDataReader reader = cmd.ExecuteReader();
            int iResult = 0;
            while (reader.Read())
            {
                reader.GetString(0);
                iResult++;
            }
            conn.Close();
     }
```
### Configuration
*Driver version:* 1.0.5

*Dotnet framework and version:* net framework 4.7

*Server version:* 3.15.2

*Client OS:* Windows Server 2016 Data Center

**Comment by howryu** [comment]
It looks like #105, and it seems that 1.0.6 fix the issue. Can you try 1.0.6 first? Also, remember that SnowflakeDbConnection object is not thread safe. Closing the connection from multiple thread will cause problem.

**Comment by Ferprimart** [comment]
Hi Haowei! I’ll try with the 1.0.6 version and let you know as soon as I have the results. About the second point you mentioned, in an API that is being called so many times it would not be any problem, right? At the end, we are creating a new instance of the connection in every new request.

Thanks for your support!

**Comment by Ferprimart** [comment]
Hi again, it’s still failing... I’ll try to use de connection using “using”, I’ll let you know asap

**Comment by howryu** [comment]
Can you enable logging or paste the stacktrace? I did not close the connection explicitly in Dispose method.

**Comment by Ferprimart** [comment]
Hi @howryu sorry for the delay but we were facing a lot of issues while trying to enable the logging... Here you have the log info related with the error we are talking:

`2019-03-07 16:53:43,414] [119] [DEBUG] [Snowflake.Data.Core.HttpUtil+RetryHandler] SF rest request timeout.
[2019-03-07 16:53:43,418] [119] [DEBUG] [Snowflake.Data.Core.HttpUtil+RetryHandler] SF rest request timeout.
[2019-03-07 16:53:43,419] [36] [ERROR] [Snowflake.Data.Core.SFStatement] Query execution failed.
System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Snowflake.Data.Core.RestRequestImpl.Post[T](SFRestRequest postRequest)
   at Snowflake.Data.Core.SFStatement.Execute(Int32 timeout, String sql, Dictionary`2 bindings, Boolean describeOnly)
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

[2019-03-07 16:53:43,420] [119] [DEBUG] [Snowflake.Data.Core.HttpUtil+RetryHandler] SF rest request timeout.
[2019-03-07 16:53:43,484] [49] [ERROR] [Snowflake.Data.Core.SFStatement] Query execution failed.
System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Snowflake.Data.Core.RestRequestImpl.Post[T](SFRestRequest postRequest)
   at Snowflake.Data.Core.SFStatement.Execute(Int32 timeout, String sql, Dictionary`2 bindings, Boolean describeOnly)
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---`

Thanks!

**Comment by howryu** [comment]
This loos like request time out. So either you had a bad network or you got throttled by server.

**Comment by zlatinal** [comment]
Any update on this issue, we seem to be experiencing similar behaviour?

**Comment by howryu** [comment]
@zlatinal Do you have the log files?

**Comment by zlatinal** [comment]
@howryu 

System.AggregateException:
   at System.Threading.Tasks.Task`1.GetResultCore (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Threading.Tasks.Task`1.get_Result (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Snowflake.Data.Core.RestRequestImpl.Post (Snowflake.Data, Version=1.0.7.0, Culture=neutral, PublicKeyToken=null)
   at Snowflake.Data.Core.SFSession.close (Snowflake.Data, Version=1.0.7.0, Culture=neutral, PublicKeyToken=null)
   at Snowflake.Data.Client.SnowflakeDbConnection.Close (Snowflake.Data, Version=1.0.7.0, Culture=neutral, PublicKeyToken=null)
 ....

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
