### ISSUE TITLE
SNOW-352097: ExternalBrowser authentication type does not work for .NET Core projects on Windows, Linux or Mac

### ISSUE THREAD

**Issue by sfc-gh-dodievich** [snowflakedb/snowflake-connector-net#308]
## Issue Description
When using ExternalBrowser authentication type, URL to the SSO provider is constructed and a browser window is opened using default OS browser. The code to start it is in Snowflake.Data.Core.Authenticator.ExternalBrowserAuthenticator.StartBrowser
https://github.com/snowflakedb/snowflake-connector-net/blob/master/Snowflake.Data/Core/Authenticator/ExternalBrowserAuthenticator.cs#L156-L174
```CS
        private static void StartBrowser(string url)
        {
            // The following code is learnt from https://brockallen.com/2016/09/24/process-start-for-urls-on-net-core/
#if NETFRAMEWORK
            // .net standard would pass here
            Process.Start(url);
#else
            // hack because of this: https://github.com/dotnet/corefx/issues/10361
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                url = url.Replace("&", "^&");
                Process.Start(new ProcessStartInfo("cmd", $"/c start {url}") { CreateNoWindow = true });
            }
            else
            {
                throw new SnowflakeDbException(SFError.UNSUPPORTED_PLATFORM);
            }
#endif
        }
```

The logic of the https://github.com/snowflakedb/snowflake-connector-net/blob/master/Snowflake.Data/Core/Authenticator/ExternalBrowserAuthenticator.cs#L159 is incorrect. 

The `NETFRAMEWORK` preprocessor symbol is used to conditionally compile in `Process.Start(url)` for what the comments suggest are .NET Standard. 
```cs
#if NETFRAMEWORK
            // .net standard would pass here
            Process.Start(url);
```

However, per https://docs.microsoft.com/en-us/dotnet/standard/frameworks#how-to-specify-a-target-framework, `NETFRAMEWORK` preprocessor symbol is for ".NET Framework", not 'NET Standard". 

## Looking at Result of Compilation

When compiled, the DLL in the `C:\snowflake\snowflake-connector-net\Snowflake.Data\bin\Release\net472\Snowflake.Data.dll` as well as in the public nuget package `C:\Users\Daniel\Downloads\snowflake.data.2.0.0\lib\net472\Snowflake.Data.dll` that is targeting .NET Full Framework for Windows Only desktops, which works fine on Windows:

```CS
// Snowflake.Data.Core.Authenticator.ExternalBrowserAuthenticator
using System.Diagnostics;

private static void StartBrowser(string url)
{
    Process.Start(url);
}
```

Looking at the DLL that targets .NET Core in `C:\snowflake\snowflake-connector-net\Snowflake.Data\bin\Release\netstandard2.0\Snowflake.Data.dll` and in `C:\Users\Daniel\Downloads\snowflake.data.2.0.0\lib\netstandard2.0\Snowflake.Data.dll`, that would be used by code running on Mac and Linux, we can see that code that could only run on Windows (and it does run beautifully there), but throws an SnowflakeDbException for Mac and Linux:

```cs
// Snowflake.Data.Core.Authenticator.ExternalBrowserAuthenticator
using Snowflake.Data.Client;
using System.Diagnostics;
using System.Runtime.InteropServices;

private static void StartBrowser(string url)
{
    if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
    {
        url = url.Replace("&", "^&");
        Process.Start(new ProcessStartInfo("cmd", $"/c start {url}")
        {
            CreateNoWindow = true
        });
        return;
    }
    throw new SnowflakeDbException(SFError.UNSUPPORTED_PLATFORM);
}
```

## Possible Solution 1
This seems like an honest mistake, and can most easily be fixed by changing to correct preprocessor symbol `NETSTANDARD2_1` or better yet `NET`:
```cs
#if NET
            // .net standard would pass here
            Process.Start(url);
```

## Possible Solution 2
Better yet, change the code to explicitly address 3 different OS versions. In fact https://brockallen.com/2016/09/24/process-start-for-urls-on-net-core/ that is mentioned in comments does just that.

**Comment by sfc-gh-dodievich** [comment]
Upon further testing, the ExternalBrowser authentication does not work on any platform. 
using this connection string:
```cs
            string connectionString = String.Format(
                "host={0};account={1};role={2};db={3};schema={4};warehouse={5};user={6};authenticator={7}",
                "instacart.snowflakecomputing.com",
                "instacart",
                "ACCOUNTADMIN",
                "SANDBOX_DB",
                "DANIELODIEVICH",
                "SNOWFLAKE_SUPPORT_WH",
                "dodievich", 
                "externalbrowser");
```

## Windows
conn.Open produces this: 
```
[2021-05-03 14:50:14,763] [1] [DEBUG] [Snowflake.Data.Client.SnowflakeDbConnection] Open Connection.
[2021-05-03 14:50:14,772] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Start parsing connection string.
[2021-05-03 14:50:14,775] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: HOST, value: instacart.snowflakecomputing.com
[2021-05-03 14:50:14,775] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: ACCOUNT, value: instacart
[2021-05-03 14:50:14,776] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: ROLE, value: ACCOUNTADMIN
[2021-05-03 14:50:14,776] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: DB, value: SANDBOX_DB
[2021-05-03 14:50:14,776] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: SCHEMA, value: DANIELODIEVICH
[2021-05-03 14:50:14,776] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: WAREHOUSE, value: SNOWFLAKE_SUPPORT_WH
[2021-05-03 14:50:14,776] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: USER, value: dodievich
[2021-05-03 14:50:14,776] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: AUTHENTICATOR, value: externalbrowser
[2021-05-03 14:50:14,782] [1] [DEBUG] [Snowflake.Data.Core.SFSessionProperties] Sesssion property PORT set to default value: 443
[2021-05-03 14:50:14,783] [1] [DEBUG] [Snowflake.Data.Core.SFSessionProperties] Sesssion property SCHEME set to default value: https
[2021-05-03 14:50:14,783] [1] [DEBUG] [Snowflake.Data.Core.SFSessionProperties] Sesssion property CONNECTION_TIMEOUT set to default value: 0
[2021-05-03 14:50:14,783] [1] [DEBUG] [Snowflake.Data.Core.SFSessionProperties] Sesssion property VALIDATE_DEFAULT_PARAMETERS set to default value: true
[2021-05-03 14:50:14,785] [1] [DEBUG] [Snowflake.Data.Core.SFSession] Open Session
[2021-05-03 14:50:14,798] [1] [INFO ] [Snowflake.Data.Core.Authenticator.ExternalBrowserAuthenticator] External Browser Authentication
[2021-05-03 14:50:14,867] [1] [DEBUG] [Snowflake.Data.Core.Authenticator.ExternalBrowserAuthenticator] Get IdpUrl and ProofKey
[2021-05-03 14:50:16,321] [1] [DEBUG] [Snowflake.Data.Core.Authenticator.ExternalBrowserAuthenticator] Open browser
[2021-05-03 14:50:17,826] [1] [ERROR] [Snowflake.Data.Client.SnowflakeDbConnection] Unable to connect
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at Snowflake.Data.Core.Authenticator.ExternalBrowserAuthenticator.StartBrowser(String url) in C:\snowflake\snowflake-connector-net\Snowflake.Data\Core\Authenticator\ExternalBrowserAuthenticator.cs:line 161
   at Snowflake.Data.Core.Authenticator.ExternalBrowserAuthenticator.Snowflake.Data.Core.Authenticator.IAuthenticator.Authenticate() in C:\snowflake\snowflake-connector-net\Snowflake.Data\Core\Authenticator\ExternalBrowserAuthenticator.cs:line 112
   at Snowflake.Data.Core.SFSession.Open() in C:\snowflake\snowflake-connector-net\Snowflake.Data\Core\SFSession.cs:line 135
   at Snowflake.Data.Client.SnowflakeDbConnection.Open() in C:\snowflake\snowflake-connector-net\Snowflake.Data\Client\SnowflakeDbConnection.cs:line 108
[2021-05-03 14:50:18,837] [1] [DEBUG] [Snowflake.Data.Client.SnowflakeDbConnection] Close Connection.
```

That is coming straight from https://github.com/snowflakedb/snowflake-connector-net/blob/master/Snowflake.Data/Core/Authenticator/ExternalBrowserAuthenticator.cs#L161

## Mac
On Mac the situation is identical
```
[2021-05-03 15:01:55,986] [1] [DEBUG] [Snowflake.Data.Client.SnowflakeDbConnection] Open Connection.
[2021-05-03 15:01:55,995] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Start parsing connection string.
[2021-05-03 15:01:55,998] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: HOST, value: instacart.snowflakecomputing.com
[2021-05-03 15:01:55,998] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: ACCOUNT, value: instacart
[2021-05-03 15:01:55,998] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: ROLE, value: ACCOUNTADMIN
[2021-05-03 15:01:55,998] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: DB, value: SANDBOX_DB
[2021-05-03 15:01:55,998] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: SCHEMA, value: DANIELODIEVICH
[2021-05-03 15:01:55,998] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: WAREHOUSE, value: SNOWFLAKE_SUPPORT_WH
[2021-05-03 15:01:55,998] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: USER, value: dodievich
[2021-05-03 15:01:55,998] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: AUTHENTICATOR, value: externalbrowser
[2021-05-03 15:01:56,001] [1] [DEBUG] [Snowflake.Data.Core.SFSessionProperties] Sesssion property PORT set to default value: 443
[2021-05-03 15:01:56,001] [1] [DEBUG] [Snowflake.Data.Core.SFSessionProperties] Sesssion property SCHEME set to default value: https
[2021-05-03 15:01:56,002] [1] [DEBUG] [Snowflake.Data.Core.SFSessionProperties] Sesssion property CONNECTION_TIMEOUT set to default value: 0
[2021-05-03 15:01:56,002] [1] [DEBUG] [Snowflake.Data.Core.SFSessionProperties] Sesssion property VALIDATE_DEFAULT_PARAMETERS set to default value: true
[2021-05-03 15:01:56,003] [1] [DEBUG] [Snowflake.Data.Core.SFSession] Open Session
[2021-05-03 15:01:56,104] [1] [INFO ] [Snowflake.Data.Core.Authenticator.ExternalBrowserAuthenticator] External Browser Authentication
[2021-05-03 15:01:56,418] [1] [DEBUG] [Snowflake.Data.Core.Authenticator.ExternalBrowserAuthenticator] Get IdpUrl and ProofKey
[2021-05-03 15:01:57,452] [1] [DEBUG] [Snowflake.Data.Core.Authenticator.ExternalBrowserAuthenticator] Open browser
[2021-05-03 15:01:57,456] [1] [ERROR] [Snowflake.Data.Client.SnowflakeDbConnection] Unable to connect
System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at Snowflake.Data.Core.Authenticator.ExternalBrowserAuthenticator.StartBrowser(String url) in C:\snowflake\snowflake-connector-net\Snowflake.Data\Core\Authenticator\ExternalBrowserAuthenticator.cs:line 161
   at Snowflake.Data.Core.Authenticator.ExternalBrowserAuthenticator.Snowflake.Data.Core.Authenticator.IAuthenticator.Authenticate() in C:\snowflake\snowflake-connector-net\Snowflake.Data\Core\Authenticator\ExternalBrowserAuthenticator.cs:line 112
   at Snowflake.Data.Core.SFSession.Open() in C:\snowflake\snowflake-connector-net\Snowflake.Data\Core\SFSession.cs:line 135
   at Snowflake.Data.Client.SnowflakeDbConnection.Open() in C:\snowflake\snowflake-connector-net\Snowflake.Data\Client\SnowflakeDbConnection.cs:line 108
[2021-05-03 15:01:57,640] [1] [DEBUG] [Snowflake.Data.Client.SnowflakeDbConnection] Close Connection.
```

**Comment by peracto** [comment]
FYI,

I'm using the connector on my Mac and PC using dotnet core.
I've included the changes that I needed to make below.


```
private static HttpListener GetHttpListener(int port)
        {
            string redirectURI = $"http://{IPAddress.Loopback}:{port}/";
            HttpListener listener = new HttpListener();
            listener.Prefixes.Add(redirectURI);
            listener.Prefixes.Add($"http://localhost:{port}/");
            return listener;
        }

        private static void StartBrowser(string url)
        {
            // The following code is learnt from https://brockallen.com/2016/09/24/process-start-for-urls-on-net-core/
#if NET46
            // .net standard would pass here
            Process.Start(url);
#else
            // hack because of this: https://github.com/dotnet/corefx/issues/10361
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                Process.Start(new ProcessStartInfo("cmd", $"/c start {url.Replace("&", "^&")}") { CreateNoWindow = true });
            }
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
            {
                Process.Start("xdg-open", url);
            }
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
            {
                Process.Start("open", url);
            }
            else
            {
                throw new SnowflakeDbException(SFError.UNSUPPORTED_PLATFORM);
            }
#endif
        }

```

**Comment by sfc-gh-dodievich** [comment]
So I must stand just a bit corrected, my previous errors were with privately built copy of this where I changes project file targets from `netstandard2.0;net472` to `net5` which negates this:
```xml
  <PropertyGroup Condition="$([System.Text.RegularExpressions.Regex]::IsMatch('$(TargetFramework)', '^net\d'))">
	<DefineConstants>NETFRAMEWORK</DefineConstants>
  </PropertyGroup>
```

If I run the code with public assembly from nuget, the errors on Mac and Linux are slightly different:
```
[2021-05-04 08:44:18,195] [1] [DEBUG] [Snowflake.Data.Core.SFSession] Open Session
[2021-05-04 08:44:18,201] [1] [INFO ] [Snowflake.Data.Core.Authenticator.ExternalBrowserAuthenticator] External Browser Authentication
[2021-05-04 08:44:18,247] [1] [DEBUG] [Snowflake.Data.Core.Authenticator.ExternalBrowserAuthenticator] Get IdpUrl and ProofKey
[2021-05-04 08:44:18,862] [1] [DEBUG] [Snowflake.Data.Core.Authenticator.ExternalBrowserAuthenticator] Open browser
[2021-05-04 08:44:18,868] [1] [ERROR] [Snowflake.Data.Client.SnowflakeDbConnection] Unable to connect
Error: OS platform is not supported. SqlState: , VendorCode: 270012, QueryId: 
[2021-05-04 08:44:18,880] [1] [DEBUG] [Snowflake.Data.Client.SnowflakeDbConnection] Close Connection.
```
That is of course thrown by https://github.com/snowflakedb/snowflake-connector-net/blob/master/Snowflake.Data/Core/Authenticator/ExternalBrowserAuthenticator.cs#L171

**Comment by sfc-gh-hkapre** [comment]
@sfc-gh-dodievich The .NET connector is only supported today on Windows. Mac and Linux are not supported. PR #338 should address the issue for Windows.

**Comment by alexrosenfeld10** [comment]
@sfc-gh-hkapre Is that really true? I would imagine there are lots of users for this that use this in C# .NET Core / .NET 5 on Linux. I know I do across tons of apps. Maybe it's just this external browser auth piece that doesn't work cross platform?

**Comment by tpiscaglia** [comment]
This is still an issue.  I've had to manually edit the source code to get this to work on my machine.  It's an easy fix so is there any idea when this will go in?

**Comment by pjrellum** [comment]
I can confirm after debugging the failure to open a browser window on my Windows/dotnet core application

**Comment by colgreen-payroc** [comment]
This still fails for a .NET 6 [core] app running on Windows.

Looking at the packaged dll for the net6.0 target we can start to see the problem; decompiling in ILSpy shows the following:

```c#
private static void StartBrowser(string url)
{
	string pattern = "^http(s?)\\:\\/\\/[0-9a-zA-Z]([-.\\w]*[0-9a-zA-Z@:])*(:(0-9)*)*(\\/?)([a-zA-Z0-9\\-\\.\\?\\,\\&\\(\\)\\/\\\\\\+&%\\$#_=@]*)?$";
	Match match = Regex.Match(url, pattern, RegexOptions.IgnoreCase);
	if (!match.Success)
	{
		logger.Error("Failed to start browser. Invalid url.");
		throw new SnowflakeDbException(SFError.INVALID_BROWSER_URL);
	}
	if (!Uri.IsWellFormedUriString(url, UriKind.Absolute))
	{
		logger.Error("Failed to start browser. Invalid url.");
		throw new SnowflakeDbException(SFError.INVALID_BROWSER_URL);
	}
	Process.Start(url);
}
```



I.e., `Process.Start(url)` is compiled into this dll, but that is the approach that works for the legacy .NET Framework only.

Looking at the source code we see:

```c#
            // The following code is learnt from https://brockallen.com/2016/09/24/process-start-for-urls-on-net-core/
#if NETFRAMEWORK
            // .net standard would pass here
            Process.Start(url);
#else
```


So there has been an attempt to not use `Process.Start()` for dotnet core builds, but that has gone wrong here. The reason is because the `Snowflake.Data.csproj` file explicitly defines the compiler constant `NETFRAMEWORK` for **all** targets.

```
<DefineConstants>NETFRAMEWORK</DefineConstants>
```

I believe that line can simply be removed from the csproj file, because `NETFRAMEWORK` is one of the standard preprocessor symbols that apply when a build targets any of the legacy .NET Framework versions.

See here for a list of standard preprocessor symbols:
   https://learn.microsoft.com/en-us/dotnet/core/tutorials/libraries#how-to-multitarget


I tried that here, and the net6.0 build dll now has the correct/intended version of `StartBrowser()` for that platform:

```
	private static void StartBrowser(string url)
{
	string regexStr = "^http(s?)\\:\\/\\/[0-9a-zA-Z]([-.\\w]*[0-9a-zA-Z@:])*(:(0-9)*)*(\\/?)([a-zA-Z0-9\\-\\.\\?\\,\\&\\(\\)\\/\\\\\\+&%\\$#_=@]*)?$";
	Match i = Regex.Match(url, regexStr, RegexOptions.IgnoreCase);
	if (!i.Success)
	{
		logger.Error("Failed to start browser. Invalid url.");
		throw new SnowflakeDbException(SFError.INVALID_BROWSER_URL);
	}
	if (!Uri.IsWellFormedUriString(url, UriKind.Absolute))
	{
		logger.Error("Failed to start browser. Invalid url.");
		throw new SnowflakeDbException(SFError.INVALID_BROWSER_URL);
	}
	if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
	{
		url = url.Replace("&", "^&");
		Process.Start(new ProcessStartInfo("cmd", "/c start " + url)
		{
			UseShellExecute = true
		});
		return;
	}
	if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
	{
		Process.Start("xdg-open", url);
		return;
	}
	if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
	{
		Process.Start("open", url);
		return;
	}
	throw new SnowflakeDbException(SFError.UNSUPPORTED_PLATFORM);
}
```

@sfc-gh-hkapre @sfc-gh-dodievich would be good to get this fixed given that it's a simple change. 

Thanks.

**Comment by ohthatwright** [comment]
I can confirm that .Net 6 is not working with externalbrowser authentication: I am getting the same exception. Please consider expediting review of the PR by @colgreen-payroc  above, @sfc-gh-dodievich @sfc-gh-hkapre @sfc-gh-jfan @sfc-gh-aaarora @sfc-gh-aaggarwal 
We may be a essentially one line fix away from being able to use .NET 6 with sso.
Happening with Snowflake.Data Nuget package 2.0.20.

**Comment by davidhcar** [comment]
I just realized this issue already going after creating #592, I have the fix in place. Could someone grant me access to push the changes and create PR ? Its inside the regex pattern in .csproj for constant NETFRAMEWORK

**Comment by ohthatwright** [comment]
@davidhcar: @colgreen-payroc has already posted a PR link above: https://github.com/snowflakedb/snowflake-connector-net/pull/575.
Great minds think alike. I looked at #592 and you and Colin have analyzed it down to the same basic cause. Colin's PR removes a preprocessor symbol from the csproj file to fix.

**Comment by colgreen-payroc** [comment]
@sfc-gh-dodievich @sfc-gh-hkapre @sfc-gh-jfan @sfc-gh-aaarora @sfc-gh-aaggarwal Please can you direct us to someone who can get the fix from PR #575 merged? Thank you.

**Comment by ohthatwright** [comment]
An opportunity is being missed here in my opinion. This is a security issue (it's important to be able to use non-password based workflows during development, being able to rely on the developers' enterprise identity while experiments are being crafted).

The fix to this issue is being served up on a silver platter via the PR. It's too bad this couldn't be gotten into the most recent release.

I am currently downloading source, applying the fix (a trivial 10 second edit) and making a custom Visual Studio project available inhouse so that people can set a dependency to that project. All of this, instead of simply using the NuGet dependency. If somebody could check this out, there is a high degree of probability that externalbrowser authentication would be working in .Net 6 within a few hours of sanity check testing.

If this fix gets completed, it greatly improves the enterprise value of the connector.

**Comment by cyril090** [comment]
Hello, 

I am facing the same kind of error on windows (Visual Studio 2022)
I am trying to connect to Snowflake from a dotnet app using Snowflake.Data wrapped around "EFCore.Snowflake". I am using the below connection string : 
"account=XXXXXX.eu-north-1.aws;user=XXXXXX;authenticator=externalbrowser;role=XXXXXXX;db=XXXXX;schema=XXXXX;warehouse=XXXXXX"

I tried many different combination of strings with externalbrowser but none of them is working: 

Snowflake.Data.Client.SnowflakeDbException (0x80004005): Error: Snowflake Internal Error: Unable to connect. One or more errors occurred. (A task was canceled.) SqlState: 08006, VendorCode: 270001, QueryId: 
 ---> System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Snowflake.Data.Core.RestRequester.Post[T](IRestRequest request)
   at Snowflake.Data.Core.Authenticator.ExternalBrowserAuthenticator.Snowflake.Data.Core.Authenticator.IAuthenticator.Authenticate()
   at Snowflake.Data.Core.SFSession.Open()
   at Snowflake.Data.Core.Session.SessionPool.NewSession(String connectionString, SecureString password, SecureString passcode, SessionCreationToken sessionCreationToken)
   at Snowflake.Data.Core.Session.SessionPool.NewNonPoolingSession(String connectionString, SecureString password, SecureString passcode)
   at Snowflake.Data.Core.Session.SessionPool.GetSession(String connStr, SecureString password, SecureString passcode)
   at Snowflake.Data.Core.Session.SessionPool.GetSession(SecureString passcode)
   at Snowflake.Data.Core.Session.ConnectionPoolManager.GetSession(String connectionString, SecureString password, SecureString passcode)
   at Snowflake.Data.Client.SnowflakeDbConnectionPool.GetSession(String connectionString, SecureString password, SecureString passcode)
   at Snowflake.Data.Client.SnowflakeDbConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at EFCore.Snowflake.Storage.Internal.SnowflakeConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at EFCore.Snowflake.Storage.SnowflakeDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase..ctor(OperationExecutor executor, IOperationResultHandler resultHandler, IDictionary args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Microsoft.EntityFrameworkCore.Tools.ReflectionOperationExecutor.Execute(String operationName, Object resultHandler, IDictionary arguments)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid4[T0,T1,T2,T3](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at Microsoft.EntityFrameworkCore.Tools.OperationExecutorBase.InvokeOperationImpl(String operationName, IDictionary arguments)
   at Microsoft.EntityFrameworkCore.Tools.OperationExecutorBase.InvokeOperation(String operation, IDictionary arguments)
   at Microsoft.EntityFrameworkCore.Tools.OperationExecutorBase.UpdateDatabase(String migration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Tools.Commands.DatabaseUpdateCommand.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
