### ISSUE TITLE
SNOW-352304: Exception handling in the connection failure do not follow best practices

### ISSUE THREAD

**Issue by sfc-gh-dodievich** [snowflakedb/snowflake-connector-net#309]
### Issue description
The code on the connection class (https://github.com/snowflakedb/snowflake-connector-net/blob/master/Snowflake.Data/Client/SnowflakeDbConnection.cs#L102-L118) that handles failures in establishing connection to snowflake does not follow the best practices of exception handling:

```cs
        public override void Open()
        {
            logger.Debug("Open Connection.");
            SetSession();
            try
            {
                SfSession.Open();
            }
            catch (Exception e)
            {
                // Otherwise when Dispose() is called, the close request would timeout.
                _connectionState = ConnectionState.Closed;
                logger.Error("Unable to connect", e);
                throw e;
            }
            OnSessionEstablished();
        }
```

Specifically, `throw e` here creates a new stack trace and destroys stack trace from the originating depths of the code, making new exception much less useful.

Thus, this:
```
[2021-05-03 15:01:57,456] [1] [ERROR] [Snowflake.Data.Client.SnowflakeDbConnection] Unable to connect
System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at Snowflake.Data.Core.Authenticator.ExternalBrowserAuthenticator.StartBrowser(String url) in C:\snowflake\snowflake-connector-net\Snowflake.Data\Core\Authenticator\ExternalBrowserAuthenticator.cs:line 161
   at Snowflake.Data.Core.Authenticator.ExternalBrowserAuthenticator.Snowflake.Data.Core.Authenticator.IAuthenticator.Authenticate() in C:\snowflake\snowflake-connector-net\Snowflake.Data\Core\Authenticator\ExternalBrowserAuthenticator.cs:line 112
   at Snowflake.Data.Core.SFSession.Open() in C:\snowflake\snowflake-connector-net\Snowflake.Data\Core\SFSession.cs:line 135
   at Snowflake.Data.Client.SnowflakeDbConnection.Open() in C:\snowflake\snowflake-connector-net\Snowflake.Data\Client\SnowflakeDbConnection.cs:line 108

```

.. becomes a considerably less useful this in the code consuming the library:
```
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at Snowflake.Data.Client.SnowflakeDbConnection.Open() in C:\snowflake\snowflake-connector-net\Snowflake.Data\Client\SnowflakeDbConnection.cs:line 115
   at dotnetconsole.Program.Main(String[] args) in C:\snowflake\.NET Connector Tests\dotnetconsole5\Program.cs:line 55
```

See https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions#place-throw-statements-so-that-the-stack-trace-will-be-helpful

### Better way 
To signal things better, either just throw the error:

```cs
        public override void Open()
        {
            logger.Debug("Open Connection.");
            SetSession();
            try
            {
                SfSession.Open();
            }
            catch (Exception e)
            {
                // Otherwise when Dispose() is called, the close request would timeout.
                _connectionState = ConnectionState.Closed;
                logger.Error("Unable to connect", e);
                throw;
            }
            OnSessionEstablished();
        }
```

or wrap the original exception in a new one, preserving original exception's call stack:
```cs
        public override void Open()
        {
            logger.Debug("Open Connection.");
            SetSession();
            try
            {
                SfSession.Open();
            }
            catch (Exception e)
            {
                // Otherwise when Dispose() is called, the close request would timeout.
                _connectionState = ConnectionState.Closed;
                logger.Error("Unable to connect", e);
                throw new ApplicationException("Unable to connect to Snowflake", e);
            }
            OnSessionEstablished();
        }
```

**Comment by AmmonRoberts** [comment]
I've created a pull request for this issue here: #439

**Comment by sfc-gh-jtang** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link Snowflake Community is the fastest way to get a response.
