### ISSUE TITLE
Unable to connect to Snowflake database using Okta SSO

### ISSUE THREAD

**Issue by jegtugado** [snowflakedb/snowflake-connector-net#358]
### Issue description
I'm unable to connect to our Snowflake database using the connection string below:

`account=company.eu-central-1;authenticator=https://company.okta.com;host=company.eu-central-1.snowflakecomputing.com;port=443;user=user@company.com;password=XXXXX;role=PRD_SEL_ROLE;warehouse=QUERY_XSMALL_WH;db=PRD;schema=PUB_NAV;`

I am following the [https://github.com/snowflakedb/snowflake-connector-net#readme](README.md)

### Example code
```cs
            string query = @"SELECT  GETDATE()";
            using (IDbConnection conn = new SnowflakeDbConnection())
            {
                conn.ConnectionString = this.ConnectionString;
                conn.Open();
                using (IDbCommand cmd = conn.CreateCommand())
                {
                    cmd.CommandText = query;
                    IDataReader reader = cmd.ExecuteReader();
                    while (reader.Read())
                    {
                        Console.WriteLine(reader.GetString(0));
                    }
                }
            }   
```

### Error log
```
[2021-08-11 23:09:04,441] [1] [DEBUG] [Snowflake.Data.Client.SnowflakeDbConnection] Open Connection.
[2021-08-11 23:09:04,510] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Start parsing connection string.
[2021-08-11 23:09:04,514] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: ACCOUNT, value: company.eu-central-1
[2021-08-11 23:09:04,514] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: AUTHENTICATOR, value: https://company.okta.com
[2021-08-11 23:09:04,514] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: HOST, value: company.eu-central-1.snowflakecomputing.com
[2021-08-11 23:09:04,515] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: PORT, value: 443
[2021-08-11 23:09:04,515] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: USER, value: user@site.com
[2021-08-11 23:09:04,516] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: PASSWORD, value: XXXXXXXX
[2021-08-11 23:09:04,516] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: ROLE, value: PRD_SEL_ROLE
[2021-08-11 23:09:04,516] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: WAREHOUSE, value: QUERY_XSMALL_WH
[2021-08-11 23:09:04,516] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: DB, value: PRD
[2021-08-11 23:09:04,516] [1] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Connection property: SCHEMA, value: PUB_NAV
[2021-08-11 23:09:04,518] [1] [DEBUG] [Snowflake.Data.Core.SFSessionProperties] Sesssion property SCHEME set to default value: https
[2021-08-11 23:09:04,519] [1] [DEBUG] [Snowflake.Data.Core.SFSessionProperties] Sesssion property CONNECTION_TIMEOUT set to default value: 120
[2021-08-11 23:09:04,519] [1] [DEBUG] [Snowflake.Data.Core.SFSessionProperties] Sesssion property VALIDATE_DEFAULT_PARAMETERS set to default value: true
[2021-08-11 23:09:04,519] [1] [DEBUG] [Snowflake.Data.Core.SFSessionProperties] Sesssion property INSECUREMODE set to default value: false
[2021-08-11 23:09:04,519] [1] [DEBUG] [Snowflake.Data.Core.SFSessionProperties] Sesssion property USEPROXY set to default value: false
[2021-08-11 23:09:04,544] [1] [DEBUG] [Snowflake.Data.Core.HttpUtil] Get Http client for True;;;;;.
[2021-08-11 23:09:04,545] [1] [DEBUG] [Snowflake.Data.Core.HttpUtil] Http client for True;;;;; not registered. Adding.
[2021-08-11 23:09:04,732] [1] [ERROR] [Snowflake.Data.Core.SFSession] Unable to connect
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at Snowflake.Data.Core.HttpUtil.setupCustomHttpHandler(HttpClientConfig config)
   at Snowflake.Data.Core.HttpUtil.<>c__DisplayClass10_0.<RegisterNewHttpClientIfNecessary>b__1()
   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__DisplayClass5_0.<ConfigurePrimaryHttpMessageHandler>b__1(HttpMessageHandlerBuilder b)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.<>c__DisplayClass17_0.<CreateHandlerEntry>g__Configure|0(HttpMessageHandlerBuilder b)
   at Microsoft.Extensions.Http.LoggingHttpMessageHandlerBuilderFilter.<>c__DisplayClass3_0.<Configure>b__0(HttpMessageHandlerBuilder builder)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandlerEntry(String name)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.<>c__DisplayClass14_0.<.ctor>b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandler(String name)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String name)
   at Snowflake.Data.Core.HttpUtil.GetHttpClient(HttpClientConfig config)
   at Snowflake.Data.Core.SFSession..ctor(String connectionString, SecureString password)
[2021-08-11 23:09:04,795] [1] [DEBUG] [Snowflake.Data.Client.SnowflakeDbConnection] Close Connection.
[2021-08-11 23:09:04,797] [1] [INFO ] [Navigator.DataSync.Services.Logger] Exception: Error: Connection string is invalid: Unable to connect SqlState: 08006, VendorCode: 270008, QueryId: 

```

### Configuration
*Driver version:* 2.0.5.0

*Dotnet framework and version:* .net framework 4.6.1

*Server version:* 5.30.2

*Client OS:* Windows 10

**Comment by jegtugado** [comment]
After upgrading the target Dotnet framework version to 4.7.2 everything worked fine
