### ISSUE TITLE
OCSP requests are not being proxied and resulting in failure

### ISSUE THREAD

**Issue by malhotrar** [snowflakedb/snowflake-connector-net#377]
### Issue description
I am using the Snowflake.Data package behind a proxy, since none of our machines have internet access. Upon running the block of code below, i get a timeout. When I pass the insecuremode=true parameter to the connection string, it works fine. I am using a windows machine, and after turning on firewall logging, while running my code snippet, I see a flurry of requests being dropped, which appear to be for URLs like: 
ocsp.sca1b.amazontrust.com
ocsp.rootca1.amazontrust.com
ocsp.digicert.com
o.ss2.us
ocsp.rootg2.amazontrust.com

It seems that one or more places do not have the proxy threaded through. 

```
Unhandled Exception: Snowflake.Data.Client.SnowflakeDbException: Snowflake Internal Error: Unable to connect ---> System.AggregateException: One or more errors occurred. ---> Snowflake.Data.Client.SnowflakeDbException: Request reach its timeout.
   at Snowflake.Data.Core.RestRequester.<SendAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Snowflake.Data.Core.RestRequester.<SendAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Snowflake.Data.Core.RestRequester.<PostAsync>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Snowflake.Data.Core.Authenticator.BaseAuthenticator.<LoginAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Snowflake.Data.Core.Authenticator.BasicAuthenticator.<Snowflake-Data-Core-Authenticator-IAuthenticator-AuthenticateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Snowflake.Data.Core.SFSession.<OpenAsync>d__25.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Snowflake.Data.Client.SnowflakeDbConnection.<OpenAsync>b__32_0(Task previousTask)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ConsoleApp1.Program.<Main>d__0.MoveNext() in C:\Users\rmalhotra\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ConsoleApp1.Program.<Main>(String[] args)
```

### Example code
```cs
using (SnowflakeDbConnection conn = new SnowflakeDbConnection())
			{
				conn.ConnectionString = "account=AB12345;user=username;password=password;db=DATA;schema=EXCHANGE;host=ab12345.snow;USEPROXY=true;PROXYHOST=1.1.1.1;PROXYPORT=8080;PROXYUSER=user;PROXYPASSWORD=pass";

				await conn.OpenAsync(CancellationToken.None);

				await conn.CloseAsync(CancellationToken.None);
			}
```

### Error log
```
2021-09-21 12:56:25 DROP TCP 10.32.26.20 99.86.227.178 49372 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:25 DROP TCP 10.32.26.20 99.86.227.104 49373 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:25 DROP TCP 10.32.26.20 99.86.227.166 49374 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:25 DROP TCP 10.32.26.20 99.86.227.115 49375 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:25 DROP TCP 10.32.26.20 54.239.153.191 49376 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:25 DROP TCP 10.32.26.20 54.239.153.67 49377 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:25 DROP TCP 10.32.26.20 54.239.153.135 49378 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:25 DROP TCP 10.32.26.20 54.239.153.224 49379 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:25 DROP TCP 10.32.26.20 54.239.153.210 49380 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:25 DROP TCP 10.32.26.20 54.239.153.5 49381 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:25 DROP TCP 10.32.26.20 54.239.153.89 49382 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:25 DROP TCP 10.32.26.20 54.239.153.230 49383 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 23.63.246.40 49385 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 23.63.246.33 49386 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 99.86.227.192 49387 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 99.86.227.37 49388 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 99.86.227.200 49389 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 99.86.227.211 49390 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 99.84.221.229 49391 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 99.84.221.32 49392 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 99.84.221.135 49393 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 99.84.221.117 49394 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 54.239.153.212 49395 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 54.239.153.129 49396 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 54.239.153.22 49397 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 54.239.153.47 49398 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 99.86.227.178 49399 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 99.86.227.104 49400 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 99.86.227.115 49401 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 99.86.227.166 49402 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 54.239.153.47 49403 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 54.239.153.212 49404 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 54.239.153.129 49405 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 54.239.153.22 49406 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 99.86.227.178 49407 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 99.86.227.104 49408 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 99.86.227.166 49409 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 99.86.227.115 49410 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 54.239.153.191 49411 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 54.239.153.67 49412 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 54.239.153.135 49413 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 54.239.153.224 49414 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 54.239.153.210 49415 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 54.239.153.5 49416 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 54.239.153.89 49417 80 0 - 0 0 0 - - - SEND
2021-09-21 12:56:41 DROP TCP 10.32.26.20 54.239.153.230 49418 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:08 DROP TCP 10.32.26.20 23.63.246.40 49420 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:08 DROP TCP 10.32.26.20 23.63.246.33 49421 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:08 DROP TCP 10.32.26.20 23.63.246.40 49422 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:08 DROP TCP 10.32.26.20 23.63.246.33 49423 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:08 DROP TCP 10.32.26.20 23.63.246.40 49424 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:08 DROP TCP 10.32.26.20 23.63.246.33 49425 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 23.63.246.33 49435 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 23.63.246.40 49436 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 99.86.227.192 49437 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 99.86.227.37 49438 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 99.86.227.200 49439 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 99.86.227.211 49440 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 99.84.221.32 49441 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 99.84.221.229 49442 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 99.84.221.135 49443 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 99.84.221.117 49444 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 54.239.153.47 49445 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 54.239.153.129 49446 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 54.239.153.212 49447 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 54.239.153.22 49448 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 99.86.227.115 49449 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 99.86.227.104 49450 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 99.86.227.166 49451 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 99.86.227.178 49452 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 54.239.153.212 49453 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 54.239.153.129 49454 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 54.239.153.47 49455 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 54.239.153.22 49456 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 99.86.227.115 49457 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 99.86.227.178 49458 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 99.86.227.166 49459 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 99.86.227.104 49460 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 54.239.153.224 49461 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 54.239.153.191 49462 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 54.239.153.67 49463 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 54.239.153.135 49464 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 54.239.153.210 49465 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 54.239.153.5 49466 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 54.239.153.89 49467 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:47 DROP TCP 10.32.26.20 54.239.153.230 49468 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:52 DROP TCP 10.32.26.20 169.254.169.254 49469 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:57 DROP TCP 10.32.26.20 23.63.246.33 49471 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:57 DROP TCP 10.32.26.20 23.63.246.40 49472 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:57 DROP TCP 10.32.26.20 23.63.246.33 49473 80 0 - 0 0 0 - - - SEND
2021-09-21 12:57:57 DROP TCP 10.32.26.20 23.63.246.40 49474 80 0 - 0 0 0 - - - SEND
2021-09-21 12:58:07 DROP TCP 10.32.26.20 23.221.74.51 49476 80 0 - 0 0 0 - - - SEND
2021-09-21 12:58:07 DROP TCP 10.32.26.20 23.221.74.73 49477 80 0 - 0 0 0 - - - SEND
2021-09-21 12:58:08 DROP TCP 10.32.26.20 23.221.74.51 49478 80 0 - 0 0 0 - - - SEND
2021-09-21 12:58:08 DROP TCP 10.32.26.20 23.221.74.73 49479 80 0 - 0 0 0 - - - SEND
2021-09-21 12:58:08 DROP TCP 10.32.26.20 72.21.91.29 49480 80 0 - 0 0 0 - - - SEND
```
There is an example in READMD.md file showing you how to enable logging.

*Dotnet framework and version:* 4.7.2

**Comment by sfc-gh-hkapre** [comment]
@malhotrar Is this only happening on Linux?

**Comment by malhotrar** [comment]
This is happening on windows. Package version 2.0.7

**Comment by sfc-gh-hkapre** [comment]
@malhotrar Thanks, we will look into this and get back to your shortly

**Comment by sfc-gh-hkapre** [comment]
@malhotrar OCSP is not used with .NET. Can you please confirm this is happening with the .NET connector vs a different driver?

**Comment by malhotrar** [comment]
So apparently to use the client with a proxy and secure mode = true; you must set the default proxy settings in internet explorer on a windows machine without internet access (https://docs.microsoft.com/en-us/troubleshoot/browsers/description-of-cryptography-api-proxy-from-crl) otherwise the CRL calls to the OCSP do not go through a proxy

**Comment by malhotrar** [comment]
We set the registry setting / manually in IE and are able to now use the proxy with secure mode.
