### ISSUE TITLE
Error: Connection string is invalid: Invalid key value pair when password contains a ';'

### ISSUE THREAD

**Issue by TurboCooler** [snowflakedb/snowflake-connector-net#458]
### Issue description
While snowflake allows ';' in passwords, the snowflake connector for .NET does not.
It thows an invalid key-value pair error.

Example connnection string
user=adbuser;password="tZ5;zI2{zP3&bE9^2";account=somecompany.us-east-1;warehouse=WH_Dev;database=DB_DEV;schema=A_Schema4Dev

This seems to be a problem with the .NET connector as the Python Connector works without issue.

The code should honor double-quoted strings.  Code seems to do a split on ';' instead.  Should instead use a regular expression
string connstring = @"user=adbuser;password=""tZ5;zI2{zP3&bE9^2"";account=somecompany.us-east-1;warehouse=WH_Dev;database=DB_DEV;schema=A_Schema4Dev";
MatchCollection regmatch = Regex.Matches(csb.ConnectionString, @"(\w+=\w+\.*\w+-*\w+-*\d*)|(\w+=\"".+?\"")");

snowflake-connector-net/Snowflake.Data/Core/SFSessionProperty.cs
Line 126
internal static SFSessionProperties parseConnectionString(String connectionString, SecureString password)
string[] propertyEntry = connectionString.Split(';');

### Example code
```
using Snowflake.Data;
using Snowflake.Data.Client;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleSnowflake
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var csb = new SnowflakeDbConnectionStringBuilder();
            csb.Add("user", "adbuser");
            csb.Add("password", "tZ5;zI2{zP3&bE9^2");
            csb.Add("account", "somecompany.us-east-1");
            csb.Add("warehouse", "WH_Dev");
            csb.Add("database", "DB_DEV");
            csb.Add("schema", "A_Schema4Dev");
            Console.WriteLine(csb.ConnectionString);         

			# Output
			# user=adbuser;password="tZ5;zI2{zP3&bE9^2";account=somecompany.us-east-1;warehouse=WH_Dev;database=DB_DEV;schema=A_Schema4Dev

            using (IDbConnection conn = new SnowflakeDbConnection())
            {
             
                conn.ConnectionString = csb.ConnectionString;

                conn.Open();
				# Fails here with invalid key-pair exception

                conn.Close();
            }
        }
    }
}
```

### Error log
```
log4net:ERROR Exception while reading ConfigurationSettings. Check your .config file is well formed XML.
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Only one <configSections> element allowed per config file and if present must be the first child of the root <configuration> element. (C:\Users\en002ma\source\repos\ConsoleSnowflake\ConsoleSnowflake\bin\Debug\ConsoleSnowflake.exe.Config line 55)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.PrivilegedConfigurationManager.GetSection(String sectionName)
   at System.Diagnostics.DiagnosticsConfiguration.GetConfigSection()
   at System.Diagnostics.DiagnosticsConfiguration.Initialize()
   at System.Diagnostics.DiagnosticsConfiguration.get_IndentSize()
   at System.Diagnostics.TraceInternal.InitializeSettings()
   at System.Diagnostics.TraceInternal.WriteLine(String message)
   at log4net.Util.LogLog.EmitErrorLine(String message)
log4net:ERROR Exception while reading ConfigurationSettings. Check your .config file is well formed XML.
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Only one <configSections> element allowed per config file and if present must be the first child of the root <configuration> element. (C:\Users\en002ma\source\repos\ConsoleSnowflake\ConsoleSnowflake\bin\Debug\ConsoleSnowflake.exe.Config line 55)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.get_AppSettings()
   at log4net.Util.SystemInfo.GetAppSetting(String key)
log4net:ERROR Exception while reading ConfigurationSettings. Check your .config file is well formed XML.
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Only one <configSections> element allowed per config file and if present must be the first child of the root <configuration> element. (C:\Users\en002ma\source\repos\ConsoleSnowflake\ConsoleSnowflake\bin\Debug\ConsoleSnowflake.exe.Config line 55)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.get_AppSettings()
   at log4net.Util.SystemInfo.GetAppSetting(String key)
log4net:ERROR Exception while reading ConfigurationSettings. Check your .config file is well formed XML.
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Only one <configSections> element allowed per config file and if present must be the first child of the root <configuration> element. (C:\Users\en002ma\source\repos\ConsoleSnowflake\ConsoleSnowflake\bin\Debug\ConsoleSnowflake.exe.Config line 55)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.get_AppSettings()
   at log4net.Util.SystemInfo.GetAppSetting(String key)
log4net:ERROR Exception while reading ConfigurationSettings. Check your .config file is well formed XML.
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Only one <configSections> element allowed per config file and if present must be the first child of the root <configuration> element. (C:\Users\en002ma\source\repos\ConsoleSnowflake\ConsoleSnowflake\bin\Debug\ConsoleSnowflake.exe.Config line 55)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.get_AppSettings()
   at log4net.Util.SystemInfo.GetAppSetting(String key)
log4net:ERROR Exception while reading ConfigurationSettings. Check your .config file is well formed XML.
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Only one <configSections> element allowed per config file and if present must be the first child of the root <configuration> element. (C:\Users\en002ma\source\repos\ConsoleSnowflake\ConsoleSnowflake\bin\Debug\ConsoleSnowflake.exe.Config line 55)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.get_AppSettings()
   at log4net.Util.SystemInfo.GetAppSetting(String key)
log4net:ERROR Exception while reading ConfigurationSettings. Check your .config file is well formed XML.
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Only one <configSections> element allowed per config file and if present must be the first child of the root <configuration> element. (C:\Users\en002ma\source\repos\ConsoleSnowflake\ConsoleSnowflake\bin\Debug\ConsoleSnowflake.exe.Config line 55)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.get_AppSettings()
   at log4net.Util.SystemInfo.GetAppSetting(String key)

Unhandled Exception: Snowflake.Data.Client.SnowflakeDbException: Connection string is invalid: Invalid key value pair zI2{zN3&bE9^2"
   at Snowflake.Data.Core.SFSessionProperties.parseConnectionString(String connectionString, SecureString password)
   at Snowflake.Data.Core.SFSession..ctor(String connectionString, SecureString password)
   at Snowflake.Data.Client.SnowflakeDbConnection.SetSession()
   at Snowflake.Data.Client.SnowflakeDbConnection.Open()
   at ConsoleSnowflake.Program.Main(String[] args) in C:\Users\en002ma\source\repos\ConsoleSnowflake\ConsoleSnowflake\Program.cs:line 30

### Configuration
*Driver version:*
2.0.12

.net framework 4.7.2 

Windows 10

**Comment by sfc-gh-jtang** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link Snowflake Community is the fastest way to get a response.
