### ISSUE TITLE
prepare command is not implemented

### ISSUE THREAD

**Issue by dragonemp** [snowflakedb/snowflake-connector-net#495]
### Issue description
using parameter and prepare is usually the best way to avoid sql injection. but when i try to call command.prepare(), i'm getting not implemented exception

### Example code
```cs
var param = cmd.CreateParameter();
param.ParameterName = "nameQuery";
param.DbType = DbType.String;
param.Value = model.Query;
cmd.Parameters.Add(param);
...
cmd.CommandText = $"{sql}";
cmd.Prepare();
reader = cmd.ExecuteReader();
```

### Error log
```
{System.NotImplementedException: The method or operation is not implemented.
   at Snowflake.Data.Client.SnowflakeDbCommand.Prepare()
   at Integrate.Reports.Service.SnowflakeCalls.GetAccountList(AccountListRequestModel model) in /app/Integrate.Reports.Service/Snowflake.cs:line 102
   at Integrate.Reports.Gateway.ReportsModuleController.GetAccountList(AccountListRequestModel model) in /app/Integrate.Reports.Gateway/ModuleControllers/ReportsModuleController.cs:line 500
   at Integrate.Reports.ReportsModuleV2.<.ctor>b__3_3(Object context, CancellationToken cancel) in /app/Integrate.Reports.Gateway/Modules/ReportsModuleV2.cs:line 122}
```
There is an example in READMD.md file showing you how to enable logging.

### Configuration
*Driver version: 2.0.15

*Dotnet framework and version: .net core 3.1

*Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();
```

*Client OS:* E.g. Debian 8.1 (Jessie), Windows 10

**Comment by sfc-gh-dszmolka** [comment]
hello and thank you for raising this issue. apologies for the long period without response. `Prepare()` is indeed [not implemented](https://github.com/snowflakedb/snowflake-connector-net/blob/v2.0.24/Snowflake.Data/Client/SnowflakeDbCommand.cs#L233-L236) even in the latest version of the driver, so we'll take a look.
