### ISSUE TITLE
The archive entry was compressed using an unsupported compression method

### ISSUE THREAD

**Issue by scastria** [snowflakedb/snowflake-connector-net#507]
### Issue description
I am trying to read data from a query from a Macintosh running .net6 and get an exception.  The code runs fine on Windows.

### Example code
```cs
await _conn.OpenAsync();
var cmd = _conn.CreateCommand();
cmd.CommandText = @$"
SELECT date, frequency, comp_id, {string.Join(',', SnowflakeColumnMapping.MapFieldsToColumns(missingMetrics))}
FROM tbl_pet4_company_historical_cleanup
ORDER BY date, comp_id, frequency
";
var reader = await cmd.ExecuteReaderAsync();
while (await reader.ReadAsync()) {
}
```

### Error log
```
2022-08-11 15:24:58.947 DataViz[17424:1303258] The archive entry was compressed using an unsupported compression method.
2022-08-11 15:24:58.950 DataViz[17424:1303258]    at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
2022-08-11 15:24:58.950 DataViz[17424:1303258]    at System.IO.Compression.Inflater.ReadOutput(Byte* bufPtr, Int32 length, Int32& bytesRead)
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
   at System.IO.Compression.Inflater.Inflate(Span`1 destination)
   at System.IO.Compression.DeflateStream.ReadCore(Span`1 buffer)
2022-08-11 15:24:58.950 DataViz[17424:1303258]    at System.IO.Compression.DeflateStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.GZipStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Snowflake.Data.Core.FastStreamWrapper.ReadByteSlow()
2022-08-11 15:24:58.950 DataViz[17424:1303258]    at Snowflake.Data.Core.FastStreamWrapper.ReadByte()
   at Snowflake.Data.Core.ReusableChunkParser.<>c__DisplayClass2_0.<ParseChunk>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
2022-08-11 15:24:58.950 DataViz[17424:1303258]    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
2022-08-11 15:24:58.950 DataViz[17424:1303258]    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
2022-08-11 15:24:58.950 DataViz[17424:1303258]    at Snowflake.Data.Core.ReusableChunkParser.ParseChunk(IResultChunk chunk)
   at Snowflake.Data.Core.SFBlockingChunkDownloaderV3.ParseStreamIntoChunk(Stream content, IResultChunk resultChunk)
2022-08-11 15:24:58.950 DataViz[17424:1303258]    at Snowflake.Data.Core.SFBlockingChunkDownloaderV3.DownloadChunkAsync(DownloadContextV3 downloadContext)
   at Snowflake.Data.Core.SFBlockingChunkDownloaderV3.GetNextChunkAsync()
   at Snowflake.Data.Core.SFResultSet.NextAsync()
2022-08-11 15:24:58.950 DataViz[17424:1303258]    at Snowflake.Data.Client.SnowflakeDbDataReader.ReadAsync(CancellationToken cancellationToken)
   at DataViz.ViewModels.MainPageViewModel.GetHistory(Int32[] compIds, String[] metrics, String[] frequencies, Boolean GetDiscrepancies) in /Users/shawncastrianni/GIT/data_viz_app/DataViz/ViewModels/MainPageViewModel.cs:line 122```
There is an example in READMD.md file showing you how to enable logging.

### Configuration
Snowflake.Data 2.0.15
.NET6
Snowflake Server: 6.27.0
Macintosh 12.5

**Comment by sfc-gh-jtang** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link Snowflake Community is the fastest way to get a response.
