### ISSUE TITLE
Query with parametrized "in" operator fails with SnowflakeDbException

### ISSUE THREAD

**Issue by vcaraulean** [snowflakedb/snowflake-connector-net#512]
### Issue description

I'm writing a query that should take an array of integer values for `in` operator. Executing the reader fails with `SnowflakeDbException`:

```
Error: SQL compilation error: error line 1 at position 42
Bind variable ? not set. SqlState: 42601, VendorCode: 2049
```

I have two questions:
- Is my code correct and I'm using a correct approach?
- Is there a workaround to get parametrization working correctly?

### Example code

The table is empty, commands are just trying to run select statements.
```cs
// creating table and doing and using "in-line" `in` operator
using (IDbCommand cmd = conn.CreateCommand())
{
	cmd.CommandText = "create or replace temporary table putArrayBind(colA integer)";
	cmd.ExecuteNonQuery();

	cmd.CommandText = "select * from putArrayBind where colA in (1, 2, 3)";
	using var reader = cmd.ExecuteReader();
}

// Parametrized "in" operator with a single value: WORKS
using (IDbCommand cmd = conn.CreateCommand())
{
    cmd.CommandText = "select * from putArrayBind where colA in (?)";
    var p1 = cmd.CreateParameter();
    p1.ParameterName = "1";
    p1.DbType = DbType.Int32;
    p1.Value = 2;
    cmd.Parameters.Add(p1);
    using var reader = cmd.ExecuteReader();
}

// Parametrized "in" operator with an array of values: FAILS
using (IDbCommand cmd = conn.CreateCommand())
{
    cmd.CommandText = "select * from putArrayBind where colA in (?)";
    var p1 = cmd.CreateParameter();
    p1.ParameterName = "1";
    p1.DbType = DbType.Int32;
    p1.Value = new int[] { 1, 2 };
    cmd.Parameters.Add(p1);
    using var reader = cmd.ExecuteReader();
}
```

The last fragment fails with `SnowflakeDbException`:
```
Error: SQL compilation error: error line 1 at position 42
Bind variable ? not set. SqlState: 42601, VendorCode: 2049

   at Snowflake.Data.Core.SFStatement.BuildResultSet(QueryExecResponse response, CancellationToken cancellationToken)
   at Snowflake.Data.Core.SFStatement.Execute(Int32 timeout, String sql, Dictionary`2 bindings, Boolean describeOnly)
   at Snowflake.Data.Client.SnowflakeDbCommand.ExecuteInternal(Boolean describeOnly)
   at Snowflake.Data.Client.SnowflakeDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at UserQuery.Main(), line 40
```

### Configuration
*Driver version:* 2.0.15

*Dotnet framework and version:* net6

*Server version:* 6.28.0

*Client OS:* Windows 10

**Comment by vcaraulean** [comment]
Found the correct way of doing it:

If we want to have query like `select * from putArrayBind where colA in (1, 2)` then every item in the array should be an individual parameter:

```
// Parametrized "in" operator with an array of values: FAILS
using (IDbCommand cmd = conn.CreateCommand())
{
    cmd.CommandText = "select * from putArrayBind where colA in (?)";
    var p1 = cmd.CreateParameter();
    p1.ParameterName = "1";
    p1.DbType = DbType.Int32;
    p1.Value = 1;
    cmd.Parameters.Add(p1);
    var p2 = cmd.CreateParameter();
    p2.ParameterName = "2";
    p2.DbType = DbType.Int32;
    p2.Value = 2;
    cmd.Parameters.Add(p2);
    using var reader = cmd.ExecuteReader();
}
```

Will close the issue...

**Comment by BHill96** [comment]
I ran into this issue as well. I understand I can dynamically create the right amount of parameters which means this isn't a major issue, but it does feel weird I can't just bind an array. At a minimum can you talk about this in the readme? Then when people try to do this they'll see they can't bind an array for the 'in' command.
