### ISSUE TITLE
Unable to connect from local machine due to Timeout

### ISSUE THREAD

**Issue by myshon** [snowflakedb/snowflake-connector-net#559]
### Issue description
I downloaded repository and I'm trying to connect to database on my snowflake trial account. Before I run tests I put these parameters
```json
{
  "testconnection": {
    "SNOWFLAKE_TEST_USER": "myshon323",
    "SNOWFLAKE_TEST_PASSWORD": "{mypasswordhere}",
    "SNOWFLAKE_TEST_ACCOUNT": "mt24333.eu-central-1",  
    "SNOWFLAKE_TEST_WAREHOUSE": "SANDBOX_WH",
    "SNOWFLAKE_TEST_DATABASE": "SANDBOX_DB",
    "SNOWFLAKE_TEST_SCHEMA": "PUBLIC",
    "SNOWFLAKE_TEST_ROLE": "ACCOUNTADMIN",
    "SNOWFLAKE_TEST_HOST": "mt24333.eu-central-1.snowflakecomputing.com"
  }
}
```

Because it's not clear to me what value should be provied in "TEST_ACCOUNT" I tried also with account name `mt24333` (without region) or also account identifier `MKFRWIX-OU52049` with and without organization prefix. In all cases I got timeout error: 

### Error log
Stacktrace: 
```
Snowflake.Data.Client.SnowflakeDbException : Error: Snowflake Internal Error: Unable to connect. One or more errors occurred. (Error: Request reach it...

Snowflake.Data.Client.SnowflakeDbException : Error: Snowflake Internal Error: Unable to connect. One or more errors occurred. (Error: Request reach its timeout. SqlState: , VendorCode: 270007, QueryId: ) SqlState: 08006, VendorCode: 270001, QueryId: 
  ----> System.AggregateException : One or more errors occurred. (Error: Request reach its timeout. SqlState: , VendorCode: 270007, QueryId: )
  ----> Snowflake.Data.Client.SnowflakeDbException : Error: Request reach its timeout. SqlState: , VendorCode: 270007, QueryId: 
  ----> System.Threading.Tasks.TaskCanceledException : A task was canceled.
   at Snowflake.Data.Client.SnowflakeDbConnection.Open() in C:\dev\snowflake\snowflake-connector-net\Snowflake.Data\Client\SnowflakeDbConnection.cs:line 207
```

log file: 

```
[2022-12-06 11:44:04,961] [NonParallelWorker] [DEBUG] [Snowflake.Data.Client.SnowflakeDbConnection] Open Connection.
[2022-12-06 11:44:04,965] [NonParallelWorker] [DEBUG] [Snowflake.Data.Client.SnowflakeDbConnection] SnowflakeDbConnectionPool::getConnection
[2022-12-06 11:44:04,965] [NonParallelWorker] [DEBUG] [Snowflake.Data.Client.SnowflakeDbConnection] SnowflakeDbConnectionPool::initConnectionPool
[2022-12-06 11:44:04,968] [NonParallelWorker] [INFO ] [Snowflake.Data.Core.SFSessionProperties] Start parsing connection string.
[2022-12-06 11:44:04,976] [NonParallelWorker] [DEBUG] [Snowflake.Data.Core.SFSessionProperties] Sesssion property CONNECTION_TIMEOUT set to default value: 120
[2022-12-06 11:44:04,977] [NonParallelWorker] [DEBUG] [Snowflake.Data.Core.SFSessionProperties] Sesssion property AUTHENTICATOR set to default value: snowflake
[2022-12-06 11:44:04,977] [NonParallelWorker] [DEBUG] [Snowflake.Data.Core.SFSessionProperties] Sesssion property VALIDATE_DEFAULT_PARAMETERS set to default value: true
[2022-12-06 11:44:04,977] [NonParallelWorker] [DEBUG] [Snowflake.Data.Core.SFSessionProperties] Sesssion property INSECUREMODE set to default value: false
[2022-12-06 11:44:04,977] [NonParallelWorker] [DEBUG] [Snowflake.Data.Core.SFSessionProperties] Sesssion property USEPROXY set to default value: false
[2022-12-06 11:44:04,978] [NonParallelWorker] [DEBUG] [Snowflake.Data.Core.SFSessionProperties] Sesssion property DISABLERETRY set to default value: false
[2022-12-06 11:44:04,978] [NonParallelWorker] [DEBUG] [Snowflake.Data.Core.SFSessionProperties] Sesssion property FORCERETRYON404 set to default value: false
[2022-12-06 11:44:04,978] [NonParallelWorker] [DEBUG] [Snowflake.Data.Core.SFSessionProperties] Sesssion property CLIENT_SESSION_KEEP_ALIVE set to default value: false
[2022-12-06 11:44:04,979] [NonParallelWorker] [DEBUG] [Snowflake.Data.Core.HttpUtil] Http client for True;;;;;;False;False not registered. Adding.
[2022-12-06 11:44:04,981] [NonParallelWorker] [DEBUG] [Snowflake.Data.Core.SFSession] Open Session
[2022-12-06 11:44:05,015] [8] [DEBUG] [Snowflake.Data.Core.RestRequester] Executing: POST https://mt24333.eu-central-1.snowflakecomputing.com/session/v1/login-request?warehouse=SANDBOX_WH&databaseName=SANDBOX_DB&schemaName=PUBLIC&roleName=ACCOUNTADMIN&requestId=f451c717-20c1-4801-9740-9f8be1dfb055&request_guid=9afce180-5555-47e9-b042-1b5111950dcd HTTP/1.1
[2022-12-06 11:44:05,018] [8] [DEBUG] [Snowflake.Data.Core.HttpUtil+RetryHandler] Http request timeout : 00:00:16
[2022-12-06 11:44:05,018] [8] [DEBUG] [Snowflake.Data.Core.HttpUtil+RetryHandler] Rest request timeout : 00:02:00
[2022-12-06 11:44:05,038] [12] [WARN ] [Snowflake.Data.Core.HttpUtil+RetryHandler] Error occurred during request, retrying...
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.Net.Http.WinHttpException (80070057, 87): Error 87 calling WinHttpAddRequestHeaders, 'The parameter is incorrect.'.
   at System.Net.Http.WinHttpException.ThrowExceptionUsingLastError(String nameOfCalledFunction)
   at System.Net.Http.WinHttpHandler.AddRequestHeaders(SafeWinHttpHandle requestHandle, HttpRequestMessage requestMessage, CookieContainer cookies, DecompressionMethods manuallyProcessedDecompressionMethods)
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state)
   --- End of inner exception stack trace ---
```

### Configuration
*Driver version:* 2.0.19
*Dotnet framework and version:* 6.0.402
*Server version:* 6.39.0
*Client OS:* Windows 10 Enterprise 10.0.19044 Build 19044

EDIT: 
I verified my connection using SnowCD and it works correctly. I checked also python connector with credentials
```
ctx = snowflake.connector.connect(
    user='myshon323',
    password='{mypasswordhere}',
    account='mt24333.eu-central-1'
    )
```
and again it works correctly. What's wrong with my configuration for .net driver?

**Comment by sfc-gh-igarish** [comment]
Please try latest version.
