### ISSUE TITLE
Calling Close() before Dispose() results in duplicate connections in the pool

### ISSUE THREAD

**Issue by jboelter** [snowflakedb/snowflake-connector-net#607]
### Issue description

Calling Close() on a connection before Dispose() results in the connection being added to the connection pool twice if connection pooling is enabled.

### Example code
```cs

SnowflakeDbConnectionPool.ClearAllPools();

while (true) {
    Console.WriteLine($"PoolSize: { SnowflakeDbConnectionPool.GetCurrentPoolSize()}");

    using var dbConnection = new SnowflakeDbConnection("some.bad.string");
    try {
        dbConnection.Open();
    }
    catch (SnowflakeDbException ex) {
        dbConnection.Close();
    }
}
```

Output + Logging. The first time through there are no connections. However, the failed connection was added twice

```
2023-02-20 23:14:56,225 [1] DEBUG Snowflake.Data.Client.SnowflakeDbConnection [(null)] - SnowflakeDbConnectionPool::ClearAllPools
2023-02-20 23:14:56,226 [1] DEBUG Snowflake.Data.Client.SnowflakeDbConnection [(null)] - SnowflakeDbConnectionPool::initConnectionPool
PoolSize: 0
2023-02-20 23:14:58,315 [1] DEBUG Snowflake.Data.Client.SnowflakeDbConnection [(null)] - Open Connection.
2023-02-20 23:14:58,316 [1] DEBUG Snowflake.Data.Client.SnowflakeDbConnection [(null)] - SnowflakeDbConnectionPool::getConnection
2023-02-20 23:14:58,328 [1] INFO  Snowflake.Data.Core.SFSessionProperties [(null)] - Start parsing connection string.
2023-02-20 23:14:58,331 [1] WARN  Snowflake.Data.Core.SFSessionProperties [(null)] - ConnectionString: some.bad.string
System.ArgumentException: Format of the initialization string does not conform to specification starting at index 0.
   at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms, Boolean useOdbcRules)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Snowflake.Data.Core.SFSessionProperties.parseConnectionString(String connectionString, SecureString password)
2023-02-20 23:14:59,469 [1] DEBUG Snowflake.Data.Client.SnowflakeDbConnection [(null)] - Close Connection.
2023-02-20 23:14:59,470 [1] DEBUG Snowflake.Data.Client.SnowflakeDbConnection [(null)] - SnowflakeDbConnectionPool::addConnection
2023-02-20 23:14:59,951 [1] DEBUG Snowflake.Data.Client.SnowflakeDbConnection [(null)] - Close Connection.
2023-02-20 23:14:59,951 [1] DEBUG Snowflake.Data.Client.SnowflakeDbConnection [(null)] - SnowflakeDbConnectionPool::addConnection
PoolSize: 2
2023-02-20 23:15:03,340 [1] DEBUG Snowflake.Data.Client.SnowflakeDbConnection [(null)] - Open Connection.
2023-02-20 23:15:03,341 [1] DEBUG Snowflake.Data.Client.SnowflakeDbConnection [(null)] - SnowflakeDbConnectionPool::getConnection
```

### Details

`Close` calls `PostClose` which in turn adds the connection to the pool via `addConnection`. Dispose also calls `Close` resulting in duplicate sessions in the pool.

```cs

        public override void Close()
        {
            logger.Debug("Close Connection.");
            _connectionState = ConnectionState.Closed;
            PostClose();
        }

        internal void PostClose()
        {
            bool added = SnowflakeDbConnectionPool.addConnection(this);
            if (!added)
            {
                SfSession.stopHeartBeatForThisSession();
                if (SfSession != null)
                {
                    SfSession.close();
                }
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposed)
                return;

            try
            {
                this.Close();
            } 
            catch (Exception ex)
            {
                // Prevent an exception from being thrown when disposing of this object
                logger.Error("Unable to close connection", ex);
            }
            
            disposed = true;

            base.Dispose(disposing);
        }
```

[Reference](https://github.com/snowflakedb/snowflake-connector-net/blob/8f5c0c6fff1dbd1e4b737c2c146a7ef5eb0c049d/Snowflake.Data/Client/SnowflakeDbConnection.cs#LL114-L132C10)

[Dispose](https://github.com/snowflakedb/snowflake-connector-net/blob/8f5c0c6fff1dbd1e4b737c2c146a7ef5eb0c049d/Snowflake.Data/Client/SnowflakeDbConnection.cs#LL320-L338C10)

**Comment by jboelter** [comment]
There appear to be a few more interactions with the pool.

`CloseAsync` adds the connection to the Pool twice. It is directly calling `SnowflakeDbConnectionPool.addConnection(this)` and then calls `PostClose` which adds it again.

```cs
while (true) {
    Console.WriteLine($"PoolSize: {SnowflakeDbConnectionPool.GetCurrentPoolSize()}");

    using var dbConnection = new SnowflakeDbConnection("some.bad.string");
    try {
        dbConnection.Open();
    }
    catch (SnowflakeDbException ex) {
        await dbConnection.CloseAsync(CancellationToken.None);
    }
}
```

```
2023-02-20 23:27:31,031 [1] DEBUG Snowflake.Data.Client.SnowflakeDbConnection [(null)] - SnowflakeDbConnectionPool::ClearAllPools
2023-02-20 23:27:31,031 [1] DEBUG Snowflake.Data.Client.SnowflakeDbConnection [(null)] - SnowflakeDbConnectionPool::initConnectionPool
PoolSize: 0
2023-02-20 23:27:37,240 [1] DEBUG Snowflake.Data.Client.SnowflakeDbConnection [(null)] - Open Connection.
2023-02-20 23:27:37,242 [1] DEBUG Snowflake.Data.Client.SnowflakeDbConnection [(null)] - SnowflakeDbConnectionPool::getConnection
2023-02-20 23:27:37,259 [1] INFO  Snowflake.Data.Core.SFSessionProperties [(null)] - Start parsing connection string.
2023-02-20 23:27:37,262 [1] WARN  Snowflake.Data.Core.SFSessionProperties [(null)] - ConnectionString: some.bad.string
System.ArgumentException: Format of the initialization string does not conform to specification starting at index 0.
   at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms, Boolean useOdbcRules)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Snowflake.Data.Core.SFSessionProperties.parseConnectionString(String connectionString, SecureString password)
2023-02-20 23:27:39,662 [1] DEBUG Snowflake.Data.Client.SnowflakeDbConnection [(null)] - Close Connection.
2023-02-20 23:27:39,663 [1] DEBUG Snowflake.Data.Client.SnowflakeDbConnection [(null)] - SnowflakeDbConnectionPool::addConnection
2023-02-20 23:27:39,664 [1] DEBUG Snowflake.Data.Client.SnowflakeDbConnection [(null)] - SnowflakeDbConnectionPool::addConnection
2023-02-20 23:27:40,354 [1] DEBUG Snowflake.Data.Client.SnowflakeDbConnection [(null)] - Close Connection.
2023-02-20 23:27:40,354 [1] DEBUG Snowflake.Data.Client.SnowflakeDbConnection [(null)] - SnowflakeDbConnectionPool::addConnection
PoolSize: 3
```

**Comment by jboelter** [comment]
When a previously disposed/closed connection is retrieved from the Pool in `Open` or `OpenAsync` the `disposed` property is also copied. This means subsequent calls to `Dispose` on a connection won't return it to the pool (although directly calling Close still will).

```cs
        private void copy(SnowflakeDbConnection conn)
        {
            ...
            this.disposed = conn.disposed;
            ...
        }
```

**Comment by sfc-gh-igarish** [comment]
Fix in the .net  driver 2.0.23. Please try it.
