### ISSUE TITLE
401 Unauthorized exception from connector

### ISSUE THREAD

**Issue by pobutp** [snowflakedb/snowflake-connector-net#616]
### Issue description
Hello,
I discovered a nondeterministic 401 exception during the running application. At the start of the project, I implemented a connector with connection pools using the package AsyncResourcePool. In the meantime ([v2.0.14](https://github.com/snowflakedb/snowflake-connector-net/tree/v2.0.14)) connector got native connection pooling, but mine project was still using an additional package for this purpose, which resulted in double pooling. I disabled connector pooling using `SnowflakeDbConnectionPool.SetPooling(false);` to not refactor the whole codebase at this moment, as a hotfix. In the application when this happened it looks like some connections are working, but others are not, returning 401, using the same connection string.

It there any other reasons that may cause a 401 exception from the connector?

### Example code
```cs
SnowflakeDbConnection conn = connPool.Resource;
SnowflakeDbCommand cmd = CreateCommand(query, queryParams, conn);
IDataReader reader = await cmd.ExecuteReaderAsync();
```

### Error log
```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Snowflake.Data.Core.RestRequester.SendAsync(HttpRequestMessage message, TimeSpan restTimeout, CancellationToken externalCancellationToken)
   at Snowflake.Data.Core.RestRequester.SendAsync(HttpMethod method, IRestRequest request, CancellationToken externalCancellationToken)
   at Snowflake.Data.Core.RestRequester.PostAsync[T](IRestRequest request, CancellationToken cancellationToken)
   at Snowflake.Data.Core.SFStatement.ExecuteAsync(Int32 timeout, String sql, Dictionary`2 bindings, Boolean describeOnly, CancellationToken cancellationToken)
   at Snowflake.Data.Client.SnowflakeDbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
```

### Configuration
*Driver version:* 2.0.21

*Dotnet framework and version:* .Net 6.0

*Server version:* 7.7.4

*Client OS:* macOS 13.2.1 (22D68)

**Comment by sfc-gh-igarish** [comment]
Similar issue fixed in the May release of the driver i.e. 2.0.24. Please try it.
