### ISSUE TITLE
multi-statement count parameter is not working...

### ISSUE THREAD

**Issue by dss010101** [snowflakedb/snowflake-connector-net#681]
This release states that multi-statement queries are now supported via the `num_statements `parameter to cursor.execute:  https://community.snowflake.com/s/article/Snowflake-Connector-for-Python-Release-Notes

The following is some code to test this:

```
test_sql = """
set( var1, var2) = ('test1', 'test2');
select $var1, $var2
"""

#documentatiaon says use 0 for any number of statements. i get the same exception if i set it to 2 also.
cur.execute(test_sql, num_statements = 0).fetchall()
```

the exception this produces is:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/snowflake/connector/cursor.py", line 910, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/usr/local/lib/python3.11/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/usr/local/lib/python3.11/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 100132 (P0000): JavaScript execution error: Uncaught Execution of multiple statements failed on statement "set( var1, var2) = ('test1', '..." (at line 1, position 0).
Actual statement count 1 did not match the desired statement count 3. in SYSTEM$MULTISTMT at '    throw `Execution of multiple statements failed on statement {0} (at line {1}, position {2}).`.replace('{1}', LINES[i])' position 4
stackstrace: 
SYSTEM$MULTISTMT line: 10
```

Is there a proper way to handle this use case?

**Comment by dss010101** [comment]
The following works without trying to select the vars...but im not able to get any results.

```
test_sql = """
set( var1, var2) = ('test1', 'test2');
select 1, 2, 3
"""

cur.execute(test_sql , num_statements = 0).fetchall()
print([x for x in cur])
```

simply prints out: `[]`

Ultimately, i would like to load this data into pandas, but This throws an exceptions:
`cur.execute(test_sql , num_statements = 0).fetch_pandas_all()`

exception:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/snowflake/connector/cursor.py", line 1120, in fetch_pandas_all
    raise NotSupportedError
snowflake.connector.errors.NotSupportedError: Unknown error

```

**Comment by sfc-gh-dszmolka** [comment]
hi - i see you raised an issue with the  Snowflake Python Connector in the repo which is for  Snowflake .NET connector, so I'm going to close this one. Please kindly head over to the Snowflake Python Connector repo and raise the issue there for proper tracking: https://github.com/snowflakedb/snowflake-connector-python/issues

**Comment by dss010101** [comment]
Im not able to get to the issue ticket to copy it over.  Could you have given me the opportunity to do so before deleting?
